### PR TITLE
Update deps for Node 22

### PR DESCRIPTION
**Pull request by arjunyel**

### CODE REVIEW

**Comment by jayair** [comment]
Thanks! I'll test it out.

**Comment by arjunyel** [comment]
Almost all my changes come from the [terminal.shop repo](https://github.com/terminaldotshop/terminal)

**Comment by jayair** [comment]
Thanks for this, I ended up taking some parts of this and leaving the rest the same as before. I think the terminal one is a good setup too. I just want to keep this one as simple as possible for people to understand.

**Comment by arjunyel** [comment]
@jayair any chance you reconsider? My changes are just a little more and make sure people dont run into footguns with bundling (no sideEffect: false), the root typescript config makes sure infra files are treated properly, and it helps give a little more structure with each infra having specific outputs. Basically, I think it is a better starting point for beginners like me who haven't been exposed to these patterns.

Also selfishly I am making an SST course and its based on assuming these changes were made in the template 😬

**Pull request closed without merging**
